apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 310011671338.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newName: 310011671338.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newTag: 71ab6449
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
